import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin']})

export default function Home() {

  var apiKey ="ae2b4e70b35d32e161cdf1269abe5669";
  var lang = "";
  var units = "";
  const url = `https://api.openweathermap.org/data/2.5/weather?`;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input 
          value={location}
          onChange={event => setLocation(event.target.value)}
          placeholder="Enter location"
          onKeyDown={searchLocation}
          type="text"
        />
      </main>
    </div>
  )
}
